<!doctype html><html lang=en><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><title>Luca Da Rin Fioretto | Stop Using Exception</title><meta property="og:title" content="Luca Da Rin Fioretto | Stop Using Exception"><meta property="og:image" content="https://i.ibb.co/DDdTQtg7/brett-jordan-XWar9-Mb-NGUY-unsplash-65.jpg"><meta property="og:description" content="Blog post on how catching/raising Python Exception is almost always a bad idea."><meta name=description content="Blog post on how catching/raising Python Exception is almost always a bad idea."><meta name=author content="Luca Da Rin Fioretto"><link rel=apple-touch-icon sizes=180x180 href=/apple-touch-icon.png><link rel=icon type=image/png sizes=32x32 href=/favicon-32x32.png><link rel=icon type=image/png sizes=16x16 href=/favicon-16x16.png><link rel=manifest href=/site.webmanifest><link rel=mask-icon href=/safari-pinned-tab.svg color=#176d86><meta name=msapplication-TileColor content="#2b5797"><meta name=theme-color content="#ffffff"><meta name=google-site-verification content="xetOSgBfIdaeBqM4aMPpxQJzsVP7a--l6tfp-hMo8T0"><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css integrity=sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2 crossorigin=anonymous><link rel=preconnect href=https://fonts.googleapis.com><link rel=preconnect href=https://fonts.gstatic.com crossorigin><link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@600&family=Saira+Condensed:wght@500;600&family=PT+Sans&family=Saira+Extra+Condensed:wght@500;600;700&family=Inconsolata:wdth,wght@50..200,200..900&display=swap" rel=stylesheet><link rel=preload href=https://use.fontawesome.com/releases/v6.1.1/css/all.css as=style onload='this.onload=null,this.rel="stylesheet"'><noscript><link rel=stylesheet href=https://use.fontawesome.com/releases/v6.1.1/css/all.css></noscript><link rel=stylesheet type=text/css href=https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css><link rel=preload href=https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css integrity="sha512-QKC1UZ/ZHNgFzVKSAhV5v5j73eeL9EEN289eKAEFaAjgAiobVAnVv/AGuPbXsKl1dNoel3kNr6PYnSiTzVVBCw==" crossorigin=anonymous as=style onload='this.onload=null,this.rel="stylesheet"'><noscript><link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css integrity="sha512-QKC1UZ/ZHNgFzVKSAhV5v5j73eeL9EEN289eKAEFaAjgAiobVAnVv/AGuPbXsKl1dNoel3kNr6PYnSiTzVVBCw==" crossorigin=anonymous></noscript><link rel=stylesheet href=https://lucadrf.dev/css/resume.min.b9e583f15b5e7460e86017f44af9587fc0165f4f6d70aa3523704876dd272e55.css integrity="sha256-ueWD8VtedGDoYBf0SvlYf8AWX09tcKo1I3BIdt0nLlU=" media=screen><link rel=stylesheet href=https://lucadrf.dev/css/tweaks.min.b0e4e1bd32455e083ff01a9e60f558e192da461201fe79e4b7a79783f1d5d526.css integrity="sha256-sOThvTJFXgg/8BqeYPVY4ZLaRhIB/nnkt6eXg/HV1SY=" media=screen><link rel=stylesheet href=https://lucadrf.dev/css/resume-override.css></head><body id=page-top><nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id=sideNav><a class="navbar-brand js-scroll-trigger" href=#page-top><span class="d-block d-lg-none">Luca Da Rin Fioretto</span>
<span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src=/img/daro_profile.png alt>
</span></a><button class=navbar-toggler type=button data-toggle=collapse data-target=#navbarSupportedContent aria-controls=navbarSupportedContent aria-expanded=false aria-label="Toggle navigation">
<span class=navbar-toggler-icon></span></button><div class="collapse navbar-collapse" id=navbarSupportedContent><ul class=navbar-nav><li class=nav-item><a class="nav-link js-scroll-trigger" href=/#about data-target=#about>About</a></li><li class=nav-item><a class="nav-link js-scroll-trigger" href=/#skills data-target=#skills>Skills</a></li><li class=nav-item><a class="nav-link js-scroll-trigger" href=/#experience data-target=#experience>Experience</a></li><li class=nav-item><a class="nav-link js-scroll-trigger" href=/#education data-target=#education>Education</a></li><li class=nav-item><a class="nav-link js-scroll-trigger" href=/#blog data-target=#blog>Blog</a></li></ul></div></nav><div class="container-fluid p-0"><nav aria-label=breadcrumb><ol class=breadcrumb><li class=breadcrumb-item><a href=https://lucadrf.dev/>Home</a></li><li class=breadcrumb-item><a href=https://lucadrf.dev/blog/>Blogs</a></li><li class="breadcrumb-item active"><a href=https://lucadrf.dev/blog/stop-using-exception/>Stop Using Exception</a></li></ol></nav><div class="resp-container fit-breadcrumbs"><div class=fill><img src=https://i.ibb.co/DDdTQtg7/brett-jordan-XWar9-Mb-NGUY-unsplash-65.jpg alt="Scrabble tiles reading 'OWN YOUR ERROR' on a white paper background"></div></div><section class="resume-section p-3 p-lg-5 d-flex flex-column"><div class=my-auto><div class="mb-3 d-flex flex-row justify-content-between"><h2 class="portfolio mb-0"><span class=text-primary>Stop Using Exception</span></h2><span>June 22, 2025</span></div><div class=mb-5><h3 class=summary>Please refrain yourself from raising <a href=https://docs.python.org/3/library/exceptions.html#Exception><code>Exception</code></a> in Python. It doesn&rsquo;t matter if ChatGPT or Claude says it&rsquo;s okay to do it, it&rsquo;s almost always a very bad idea.</h3></div><div><h2 id=tldr class=anchored-heading>TL;DR <a class="header-link js-scroll-trigger" href=#tldr><i class="fa fa-link anchor-icons"></i></a></h2><p>Please stop raising (and in most cases catching) top level <a href=https://docs.python.org/3/library/exceptions.html#Exception><code>Exception</code></a>
in Python.</p><p>There is basically no good reason for raising <code>Exception</code> in code written for a
library, as for catching it, probably the only acceptable case would be in the
outermost layer of an application in which no exception should cause the
termination of the interpreter (e.g. a Web server) and with the unconditional
assumption that the exception is logged somewhere.</p><p>Also, if you&rsquo;re writing examples for a Python course or guide and your
code snippets catch and/or raise <code>Exception</code> please, please, please either state
very clearly that in most cases that&rsquo;s an anti-pattern or, you know, use a
different exception type 😉.</p><h2 id=introduction class=anchored-heading>Introduction <a class="header-link js-scroll-trigger" href=#introduction><i class="fa fa-link anchor-icons"></i></a></h2><p>I know there are a gazillion blog posts, videos and courses on the Interwebs
telling you that catching and/or raising <a href=https://docs.python.org/3/library/exceptions.html#Exception><code>Exception</code></a>
in Python is a no-no. And yet, I&rsquo;ve recently stumbled upon some commercial (and
fairly successful) Python library doing it, with predictably terrible results. I
won&rsquo;t reveal the name of the library as I don&rsquo;t like to naming and shaming, and
I&rsquo;ve already sent some feedback about that their way.</p><p>So why do experienced Python programmers&rsquo; grumble when they see <code>except Exception</code> in a library? And why do their right eyes start twitching when they
see <code>raise Exception</code>?</p><h2 id=the-case class=anchored-heading>The Case <a class="header-link js-scroll-trigger" href=#the-case><i class="fa fa-link anchor-icons"></i></a></h2><p>As I was working with a commercial library I ended up having to handle the following
exception being raised by the vendor HTTP client (<strong>note</strong>: I&rsquo;m only reporting the
last two formatted lines of the trace stack as the rest is not important):</p><div class=highlight><pre tabindex=0 style=background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-fallback data-lang=fallback><span style=display:flex><span>... omitted trace stack ...
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>File /my_volume/lib/python3.11/site-packages/vendor/module/utils.py:160, in HTTPUtils.send_request(url, method, token, params, json, verify, auth, data, headers)
</span></span><span style=display:flex><span>    158     response.raise_for_status()
</span></span><span style=display:flex><span>    159 except Exception as e:
</span></span><span style=display:flex><span>--&gt; 160     raise Exception(
</span></span><span style=display:flex><span>    161         f&#34;Response content {response.content}, status_code {response.status_code}&#34;
</span></span><span style=display:flex><span>    162     )
</span></span><span style=display:flex><span>    163 return response.json()
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>Exception: Response content b&#39;{&#34;error_code&#34;:&#34;NOT_FOUND&#34;,&#34;message&#34;:&#34;Resource my-resource not found.&#34;,&#34;details&#34;:[{&#34;@type&#34;:&#34;type.googleapis.com/google.rpc.RequestInfo&#34;,&#34;request_id&#34;:&#34;8da16872-3641-43cf-ab6b-3a10559bd6a3&#34;,&#34;serving_data&#34;:&#34;&#34;}]}&#39;, status_code 404
</span></span></code></pre></div><p>The above is a great example of how <strong>NOT</strong> to write library code, and if the
reason is not clear, please continue reading.</p><p>So, the above error was thrown when calling the method <code>get_resource()</code> of an
instance of said vendor client. The client class basically abstracts a series of
common operations on said vendor platform and that under the hood are performed
via HTTP requests.</p><p>In my code I was trying to get a vendor&rsquo;s <code>Resource</code> object and had something like:</p><div class=highlight><pre tabindex=0 style=background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span>client <span style=color:#0550ae>=</span> VendorClient<span style=color:#1f2328>()</span>
</span></span><span style=display:flex><span>resource <span style=color:#0550ae>=</span> client<span style=color:#0550ae>.</span>get_resource<span style=color:#1f2328>(</span><span style=color:#0a3069>&#34;my-resource&#34;</span><span style=color:#1f2328>)</span>
</span></span></code></pre></div><p>As the resource named &ldquo;my-resource&rdquo; was not found, the client threw an
exception, and that&rsquo;s okay if it wasn&rsquo;t for the <em>type</em> of such exception which
was indeed <code>Exception</code>.</p><p>That&rsquo;s bad design because <code>Exception</code> being the base class of most of Python&rsquo;s
exceptions makes it really hard for the user to handle, unless of course the
user is happy to simply catch the exception, probably log it, then either pass
or raise. See below:</p><div class=highlight><pre tabindex=0 style=background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span>client <span style=color:#0550ae>=</span> VendorClient<span style=color:#1f2328>()</span>
</span></span><span style=display:flex><span><span style=color:#cf222e>try</span><span style=color:#1f2328>:</span>
</span></span><span style=display:flex><span>    resource <span style=color:#0550ae>=</span> client<span style=color:#0550ae>.</span>get_resource<span style=color:#1f2328>(</span><span style=color:#0a3069>&#34;my-resource&#34;</span><span style=color:#1f2328>)</span>
</span></span><span style=display:flex><span><span style=color:#cf222e>except</span> Exception <span style=color:#cf222e>as</span> e<span style=color:#1f2328>:</span>
</span></span><span style=display:flex><span>    <span style=color:#57606a># At this point we can&#39;t statically infer the type of the error.</span>
</span></span><span style=display:flex><span>    <span style=color:#57606a># If the type was TimeoutError we might wanted to handle it with a retry...</span>
</span></span><span style=display:flex><span>    <span style=color:#57606a># If the type was ValueError we might wanted to add some context to it and re-raise...</span>
</span></span><span style=display:flex><span>    <span style=color:#57606a># But we&#39;ve got Exception instead so statically we can only tell that something</span>
</span></span><span style=display:flex><span>    <span style=color:#57606a># went wrong with client.get_resource() and that&#39;s it.</span>
</span></span></code></pre></div><p>For example, try to write a function that reliably returns <code>True</code> if
&ldquo;my-resource&rdquo; exist and <code>False</code> if it doesn&rsquo;t exist using <code>get_resource()</code>
(note that <code>VendorClient</code> doesn&rsquo;t implement a &ldquo;<code>resource_exists()</code>&rdquo; method).</p><p>Basically the only thing you can do is somehow parse the error message. I&rsquo;ve
asked the vendor to provide an example for the above case and below is what they
suggested:</p><div class=highlight><pre tabindex=0 style=background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#cf222e>def</span> <span style=color:#6639ba>resource_exists</span><span style=color:#1f2328>(</span>client<span style=color:#1f2328>,</span> resource_name<span style=color:#1f2328>):</span>
</span></span><span style=display:flex><span>    <span style=color:#cf222e>try</span><span style=color:#1f2328>:</span>
</span></span><span style=display:flex><span>        client<span style=color:#0550ae>.</span>get_resource<span style=color:#1f2328>(</span>resource_name<span style=color:#1f2328>)</span>
</span></span><span style=display:flex><span>        <span style=color:#cf222e>return</span> <span style=color:#cf222e>True</span>
</span></span><span style=display:flex><span>    <span style=color:#cf222e>except</span> Exception <span style=color:#cf222e>as</span> e<span style=color:#1f2328>:</span>
</span></span><span style=display:flex><span>        <span style=color:#cf222e>if</span> <span style=color:#0a3069>&#34;NOT_FOUND&#34;</span> <span style=color:#0550ae>in</span> <span style=color:#6639ba>str</span><span style=color:#1f2328>(</span>e<span style=color:#1f2328>):</span>
</span></span><span style=display:flex><span>            <span style=color:#cf222e>return</span> <span style=color:#cf222e>False</span>
</span></span><span style=display:flex><span>        <span style=color:#cf222e>else</span><span style=color:#1f2328>:</span>
</span></span><span style=display:flex><span>            <span style=color:#cf222e>raise</span> e
</span></span></code></pre></div><p>Ugh, can you see the problem now? Having to rely on the error message is an
extremely brittle solution; error messages are not designed to be interpreted
by machines, they&rsquo;re designed for humans! The structure and content of error
messages is likely to change as it&rsquo;s not part of the public API of a library. If
a vendor library changes the <em>type</em> of an exception raised by a public function
they&rsquo;re effectively introducing a breaking change, but changing the error
message of a raised exception isn&rsquo;t (and shouldn&rsquo;t be) a change that breaks
user&rsquo;s code. Is perfectly okay to not even unit-test complete error messages.</p><p>But with this vendor&rsquo;s library, error messages are basically public API.</p><p>The other annoying drawback of calling a function/method that raises <code>Exception</code>
is that forces the user to catch <code>Exception</code> hence any other operation in
the <code>try</code> block that raises an exception will be caught, forcing the user to
have a dedicated <code>try</code> block for <code>get_resource()</code> and be more verbose.</p><h2 id=a-better-design class=anchored-heading>A better design <a class="header-link js-scroll-trigger" href=#a-better-design><i class="fa fa-link anchor-icons"></i></a></h2><p>Let&rsquo;s have another look at the code reported in the error trace stack, see below:</p><div class=highlight><pre tabindex=0 style=background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span>    response<span style=color:#0550ae>.</span>raise_for_status<span style=color:#1f2328>()</span>
</span></span><span style=display:flex><span><span style=color:#cf222e>except</span> Exception <span style=color:#cf222e>as</span> e<span style=color:#1f2328>:</span>
</span></span><span style=display:flex><span>    <span style=color:#cf222e>raise</span> Exception<span style=color:#1f2328>(</span>
</span></span><span style=display:flex><span>        <span style=color:#0a3069>f</span><span style=color:#0a3069>&#34;Response content </span><span style=color:#0a3069>{</span>response<span style=color:#0550ae>.</span>content<span style=color:#0a3069>}</span><span style=color:#0a3069>, status_code </span><span style=color:#0a3069>{</span>response<span style=color:#0550ae>.</span>status_code<span style=color:#0a3069>}</span><span style=color:#0a3069>&#34;</span>
</span></span><span style=display:flex><span>    <span style=color:#1f2328>)</span>
</span></span></code></pre></div><p>If you&rsquo;ve used <a href=https://requests.readthedocs.io/en/latest/>requests</a>
library a bit you probably have noticed the
<a href=https://requests.readthedocs.io/en/latest/api/#requests.Response.raise_for_status><code>raise_for_status()</code></a>
call in the first line, and you probably know that the exception raised is
<a href=https://requests.readthedocs.io/en/latest/_modules/requests/exceptions/#HTTPError><code>requests.HTTPError</code></a>
which is a very good and feature-rich object (e.g. it contains a reference to
the <code>Response</code> objects that raised it for introspection).</p><p>So why catching it and raising a generic <code>Exception</code>? Also, why catching
<code>Exception</code> in the second line when we know that <code>raise_for_status()</code> only
raises <code>HTTPError</code>? Who knows 🤷🏻‍♂️, maybe the code was written by an AI.</p><p>I&rsquo;d fix the above code by removing the <code>except</code> block and let
<code>requests.HTTPError</code> propagate. The exception can then be caught at the
<code>VendorClient</code> level and wrapped in a custom exception, say <code>NotFoundResource</code>
alongside extra <code>VendorClient</code>-specific context.</p><p>For example:</p><div class=highlight><pre tabindex=0 style=background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#57606a># Vendor custom exceptions</span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#cf222e>class</span> <span style=color:#1f2328>ClientError</span><span style=color:#1f2328>(</span>IOError<span style=color:#1f2328>):</span>
</span></span><span style=display:flex><span>    <span style=color:#cf222e>def</span> <span style=color:#6639ba>__init__</span><span style=color:#1f2328>(</span><span style=color:#6a737d>self</span><span style=color:#1f2328>,</span> <span style=color:#0550ae>*</span>args<span style=color:#1f2328>,</span> <span style=color:#0550ae>**</span>kwargs<span style=color:#1f2328>):</span>
</span></span><span style=display:flex><span>        <span style=color:#6a737d>self</span><span style=color:#0550ae>.</span>request_error <span style=color:#0550ae>=</span> kwargs<span style=color:#0550ae>.</span>pop<span style=color:#1f2328>(</span><span style=color:#0a3069>&#34;request_error&#34;</span><span style=color:#1f2328>,</span> <span style=color:#cf222e>None</span><span style=color:#1f2328>)</span>
</span></span><span style=display:flex><span>        <span style=color:#6639ba>super</span><span style=color:#1f2328>()</span><span style=color:#0550ae>.</span><span style=color:#6639ba>__init__</span><span style=color:#1f2328>(</span><span style=color:#0550ae>*</span>args<span style=color:#1f2328>,</span> <span style=color:#0550ae>**</span>kwargs<span style=color:#1f2328>)</span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#cf222e>class</span> <span style=color:#1f2328>NotFoundResource</span><span style=color:#1f2328>(</span>ClientError<span style=color:#1f2328>):</span>
</span></span><span style=display:flex><span>    <span style=color:#cf222e>pass</span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#57606a># VendorClient.get_resource()</span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#cf222e>def</span> <span style=color:#6639ba>get_resource</span><span style=color:#1f2328>(</span>name<span style=color:#1f2328>:</span> <span style=color:#6639ba>str</span><span style=color:#1f2328>,</span> <span style=color:#0550ae>...</span><span style=color:#1f2328>):</span>
</span></span><span style=display:flex><span><span style=color:#0550ae>...</span>
</span></span><span style=display:flex><span>    <span style=color:#cf222e>try</span><span style=color:#1f2328>:</span>
</span></span><span style=display:flex><span>        response <span style=color:#0550ae>=</span> HTTPUtils<span style=color:#0550ae>.</span>send_request<span style=color:#1f2328>(</span><span style=color:#0550ae>...</span><span style=color:#1f2328>)</span>
</span></span><span style=display:flex><span>    <span style=color:#cf222e>except</span> requests<span style=color:#0550ae>.</span>HTTPError <span style=color:#cf222e>as</span> e<span style=color:#1f2328>:</span>
</span></span><span style=display:flex><span>        <span style=color:#cf222e>if</span> e<span style=color:#0550ae>.</span>response<span style=color:#0550ae>.</span>status_code <span style=color:#0550ae>==</span> <span style=color:#0550ae>404</span><span style=color:#1f2328>:</span>
</span></span><span style=display:flex><span>            <span style=color:#cf222e>raise</span> NotFoundResource<span style=color:#1f2328>(</span>request_error<span style=color:#0550ae>=</span>e<span style=color:#1f2328>)</span>
</span></span><span style=display:flex><span><span style=color:#0550ae>...</span>
</span></span></code></pre></div><p>Here&rsquo;s how <code>resource_exists()</code> implementation would look like:</p><div class=highlight><pre tabindex=0 style=background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#cf222e>def</span> <span style=color:#6639ba>resource_exists</span><span style=color:#1f2328>(</span>client<span style=color:#1f2328>,</span> resource_name<span style=color:#1f2328>):</span>
</span></span><span style=display:flex><span>    <span style=color:#cf222e>try</span><span style=color:#1f2328>:</span>
</span></span><span style=display:flex><span>        client<span style=color:#0550ae>.</span>get_resource<span style=color:#1f2328>(</span>resource_name<span style=color:#1f2328>)</span>
</span></span><span style=display:flex><span>        <span style=color:#cf222e>return</span> <span style=color:#cf222e>True</span>
</span></span><span style=display:flex><span>    <span style=color:#cf222e>except</span> NotFoundResource<span style=color:#1f2328>:</span>
</span></span><span style=display:flex><span>        <span style=color:#cf222e>return</span> <span style=color:#cf222e>False</span>
</span></span></code></pre></div><p>Much nicer don&rsquo;t you think?</p><h2 id=conclusion class=anchored-heading>Conclusion <a class="header-link js-scroll-trigger" href=#conclusion><i class="fa fa-link anchor-icons"></i></a></h2><p>Catching a specialised exception and then re-raising <code>Exception</code> (the most
generic) type, should almost always be avoided. Doing so makes it significantly
harder to handle the resulting exception effectively and adds a significant
amount of brittleness.</p><p>Before wrapping code in a <code>try/except</code> block, consider whether that&rsquo;s the right
place to handle the exceptions raised by the wrapped code. Remember that
sometimes <em>less is more</em>, and it might be better to let the exception propagate
to a higher scope.</p><p>When handling exception in library code, try to catch explicitly and precisely
the <em>type</em> expected, if possible, avoid catching classes that are too generic;
the risk being trapping exception unintentionally and ending up with
<a href=https://en.wikipedia.org/wiki/Error_hiding>Error Hiding</a>.</p><p>When raising an exception, first consider raising a Python
<a href=https://docs.python.org/3/library/exceptions.html#exception-hierarchy>built-in exception</a>,
and then consider a custom one only if the built-ins are too generic (although
they are usually enough).</p></div></div></section><span style=color:#999;font-size:60%>Copyright &copy; 2025 Luca Da Rin Fioretto.</span>
<span style=color:#999;font-size:60%>Based on <a href=https://github.com/eddiewebb/hugo-resume>hugo-resume</a> theme and generated with <a href=https://gohugo.io/>HUGO</a></span></div><script src=https://code.jquery.com/jquery-3.6.4.slim.min.js integrity="sha256-a2yjHM4jnF9f54xUQakjZGaqYs/V1CYvWpoqZzC2/Bw=" crossorigin=anonymous></script><script src=https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js integrity=sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx crossorigin=anonymous></script><script src=https://unpkg.com/smoothscroll-polyfill@0.4.4/dist/smoothscroll.min.js integrity=sha384-EYn4rWu1DHvYD0sSSSbMEtXQmMl58CFJd897806+RT1jJVYbhuZlZMN6yG9nCyFa crossorigin=anonymous></script><script src=https://unpkg.com/smoothscroll-anchor-polyfill@1.3.2/dist/index.min.js integrity=sha384-EY9NBEHCFbZANmPcTm7CgG8OhsFILy0VBLG85pF6OIpP42NVbZVNsFOc23PYTCkB crossorigin=anonymous></script><script async src=https://lucadrf.dev/js/resume.min.js></script></body></html>